sheet_names:
  details: "SP ITEMIZED REPORT"

columns:
  details:
    batch_id: "BATCH ID"
    company_name: "SP COMPANY"   
    driver_name: "DRIVER NAME"
    drive_code: "DRIVE CODE"     
    date: "DATE"
    trip_code: "TRIP CODE"
    trip_name: "TRIP NAME"
    cancellation_reason: "CANCELLATION REASON"
    miles: "MIlES"
    spiff: "SPIFF"
    gross_pay: "GROSS PAY"
    deduction: "DEDUCTION"
    net_pay: "NET PAY"
defaults:
  timezone: "America/New_York"
  currency: "USD"
  distance_unit: "miles" # convert to km for your model
